const panels = Object.fromEntries([...document.querySelectorAll('.game-panel')].map(p => [p.id.replace('-panel',''), p]));
const choices = [...document.querySelectorAll('.game-choice')];
let activeGame = 'tap';

/* --- 泡をタップ：プレイ中だけ時計を動かす --- */
const pond = document.getElementById('tap-pond'), bubble = document.getElementById('tap-bubble');
const tapState = document.getElementById('tap-state'), tapTime = document.getElementById('tap-time'), tapBest = document.getElementById('tap-best'), tapMessage = document.getElementById('tap-message');
let tapOn = false, tapCount = 0, tapStartAt = 0, tapFrame = 0;
let bestTap = Number(localStorage.getItem('aqua-tap-best')) || 0;
const showBestTap = () => tapBest.textContent = bestTap ? `${(bestTap / 1000).toFixed(2)}秒` : '--';
function stopTap() { tapOn = false; cancelAnimationFrame(tapFrame); }
function tapClock() { if (tapOn) { tapTime.textContent = `${((performance.now()-tapStartAt)/1000).toFixed(2)}秒`; tapFrame=requestAnimationFrame(tapClock); } }
function putBubble() { bubble.style.left = `${12+Math.random()*Math.max(1,pond.clientWidth-70)}px`; bubble.style.top = `${12+Math.random()*Math.max(1,pond.clientHeight-70)}px`; }
document.getElementById('tap-start').onclick=()=>{ stopTap();tapOn=true;tapCount=0;tapStartAt=performance.now();bubble.hidden=false;tapState.textContent='0 / 10';tapMessage.hidden=true;putBubble();tapClock(); };
bubble.onclick=()=>{if(!tapOn)return;tapCount++;tapState.textContent=`${tapCount} / 10`;if(tapCount<10){putBubble();return}const result=Math.round(performance.now()-tapStartAt);stopTap();bubble.hidden=true;tapTime.textContent=`${(result/1000).toFixed(2)}秒`;tapState.textContent='CLEAR!';if(!bestTap||result<bestTap){bestTap=result;localStorage.setItem('aqua-tap-best',String(result));tapMessage.textContent='ベスト更新！';}else tapMessage.textContent='10個集めました。';tapMessage.hidden=false;showBestTap();};showBestTap();bubble.hidden=true;

/* --- 深海探検：Canvas 1枚。590前後で終わる要因だった被弾連続を防ぐ --- */
const cv=document.getElementById('deep-canvas'), ctx=cv.getContext('2d');
const deepScore=document.getElementById('deep-score'), deepHp=document.getElementById('deep-hp'), deepStateLabel=document.getElementById('deep-state'), rainbowLabel=document.getElementById('rainbow-time'), deepResult=document.getElementById('deep-result');
let deepRun=false, deepFrame=0, deepLast=0, deep;
const keys=new Set();
function freshDeep(){return{sub:{x:360,y:160,r:21},score:0,hp:3,elapsed:0,level:0,shield:false,rainbow:0,invincible:0,obstacles:[],items:[],obWait:0,itWait:0,drag:false};}
function stopDeep(){deepRun=false;cancelAnimationFrame(deepFrame);keys.clear();}
function bestDeep(){return Number(localStorage.getItem('aqua-deep-best'))||0;}
function circleHit(a,b,r){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+r;}
function spawnObstacle(){const shark=Math.random()>.56;const width=shark?55:42;const tooClose=deep.obstacles.some(o=>Math.abs(o.x-(35+Math.random()*650))<70&&o.y>360);if(!tooClose)deep.obstacles.push({x:35+Math.random()*650,y:495,w:width,h:shark?25:40,type:shark?'shark':'rock'});}
function spawnItem(){const r=Math.random(),type=r<.48?'white':r<.64?'bright':r<.8?'black':r<.91?'gold':'rainbow';deep.items.push({x:35+Math.random()*650,y:485,r:11,type});}
function labels(now){deepScore.textContent=Math.max(0,Math.floor(deep.score));deepHp.innerHTML=[0,1,2].map(i=>`<span class="${i<deep.hp?'':'lost'}">${i<deep.hp?'♥':'♡'}</span>`).join(' ');const remain=Math.max(0,deep.rainbow-now);rainbowLabel.textContent=remain?`${(remain/1000).toFixed(1)}秒`:(deep.shield?'盾あり':'--');}
function collect(item,now){const special=deep.rainbow>now;if(item.type==='white')deep.score+=special?200:100;if(item.type==='bright')deep.score+=special?1000:500;if(item.type==='black')deep.score-=special?150:300;if(item.type==='gold')deep.shield=true;if(item.type==='rainbow')deep.rainbow=now+10000;}
function drawDeep(){const d=Math.min(.74,deep.level*.09),g=ctx.createLinearGradient(0,0,0,cv.height);g.addColorStop(0,`rgb(${145-d*120},${224-d*150},${245-d*100})`);g.addColorStop(1,`rgb(${18-d*12},${104-d*62},${165-d*74})`);ctx.fillStyle=g;ctx.fillRect(0,0,cv.width,cv.height);deep.items.forEach(i=>{ctx.save();ctx.translate(i.x,i.y);ctx.shadowBlur=13;ctx.shadowColor=i.type==='black'?'#26344f':'#fff';if(i.type==='rainbow'){const c=ctx.createConicGradient(0,0);['#ff8dd1','#ffe06d','#76f5d0','#769dff','#ca94ff','#ff8dd1'].forEach((x,n)=>c.addColorStop(n/5,x));ctx.fillStyle=c;}else ctx.fillStyle=i.type==='black'?'#192944':'#fff';ctx.beginPath();ctx.arc(0,0,i.r,0,7);ctx.fill();ctx.strokeStyle=['bright','gold'].includes(i.type)?'#f5c94e':'#dfffff';ctx.lineWidth=['bright','gold'].includes(i.type)?3:1;ctx.stroke();ctx.restore();});deep.obstacles.forEach(o=>{ctx.save();ctx.translate(o.x,o.y);ctx.shadowBlur=8;ctx.shadowColor='#bcefff';if(o.type==='rock'){ctx.fillStyle='#263e61';ctx.beginPath();ctx.moveTo(-o.w/2,o.h/2);ctx.lineTo(-o.w/2+7,-o.h/3);ctx.lineTo(0,-o.h/2);ctx.lineTo(o.w/2,o.h/2);ctx.fill();ctx.strokeStyle='#b9efff';ctx.stroke();}else{ctx.fillStyle='#3a6188';ctx.beginPath();ctx.ellipse(0,0,o.w/2,o.h/2,0,0,7);ctx.fill();ctx.fillStyle='#09203d';ctx.fillRect(8,-4,4,4);}ctx.restore();});const s=deep.sub;ctx.save();ctx.translate(s.x,s.y);ctx.shadowBlur=15;ctx.shadowColor='#dfffff';ctx.fillStyle='#efffff';ctx.strokeStyle='#086dab';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,29,16,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#5ac5eb';ctx.beginPath();ctx.arc(5,-2,8,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#f5cd59';ctx.fillRect(-4,15,8,6);ctx.restore();if(deep.rainbow>performance.now()){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,35,0,7);ctx.stroke();}}
function finishDeep(){stopDeep();const score=Math.max(0,Math.floor(deep.score));const high=Math.max(score,bestDeep());if(score>=high)localStorage.setItem('aqua-deep-best',String(score));deepStateLabel.textContent='GAME OVER';deepResult.textContent=`潜水時間 ${(deep.elapsed/1000).toFixed(1)}秒　最終スコア ${score}　最高スコア ${high}`;document.getElementById('deep-start').textContent='もう一度潜る';}
function deepLoop(now){if(!deepRun)return;const dt=Math.min(35,now-deepLast||16);deepLast=now;deep.elapsed+=dt;deep.level=Math.max(Math.floor(deep.elapsed/15000),Math.floor(Math.max(0,deep.score)/1000));const velocity=2.05+deep.level*.22,move=(.20+deep.level*.022)*dt;if(keys.has('ArrowLeft'))deep.sub.x-=move;if(keys.has('ArrowRight'))deep.sub.x+=move;if(keys.has('ArrowUp'))deep.sub.y-=move;if(keys.has('ArrowDown'))deep.sub.y+=move;deep.sub.x=Math.max(24,Math.min(cv.width-24,deep.sub.x));deep.sub.y=Math.max(24,Math.min(cv.height-24,deep.sub.y));deep.score+=dt*.014;deep.obWait+=dt;deep.itWait+=dt;if(deep.obWait>Math.max(620,1100-deep.level*35)){spawnObstacle();deep.obWait=0}if(deep.itWait>1650){spawnItem();deep.itWait=0}deep.obstacles.forEach(o=>o.y-=velocity*dt/16);deep.items.forEach(i=>i.y-=velocity*.78*dt/16);deep.items=deep.items.filter(i=>{if(circleHit(deep.sub,i,i.r)){collect(i,now);return false}return i.y>-28});deep.obstacles=deep.obstacles.filter(o=>{if(circleHit(deep.sub,o,Math.max(o.w,o.h)/2)){if(deep.rainbow>now)deep.score+=100;else if(deep.shield)deep.shield=false;else if(now>=deep.invincible){deep.hp--;deep.invincible=now+1100;}return false}return o.y>-55});labels(now);drawDeep();if(deep.hp<=0){finishDeep();return}deepFrame=requestAnimationFrame(deepLoop);}
document.getElementById('deep-start').onclick=()=>{stopDeep();deep=freshDeep();deepRun=true;deepLast=performance.now();deepStateLabel.textContent='潜水中';deepResult.textContent='被弾後は短時間だけ無敵になります。';labels(deepLast);drawDeep();deepFrame=requestAnimationFrame(deepLoop);};deep=freshDeep();drawDeep();

/* --- パズル1：完成盤から合法手で崩す8パズル。必ず解ける --- */
const board=document.getElementById('slide-board'),slideState=document.getElementById('slide-state');let tiles=[];
function drawSlide(){board.innerHTML='';tiles.forEach((v,i)=>{const c=document.createElement('span');c.className=v?'tile':'blank';c.textContent=v||'✦';board.appendChild(c);});}
function movable(i,empty){return Math.abs(i%3-empty%3)+Math.abs(Math.floor(i/3)-Math.floor(empty/3))===1;}
function newSlide(){tiles=[1,2,3,4,5,6,7,8,0];let empty=8,last=-1;for(let n=0;n<45;n++){const moves=[0,1,2,3,4,5,6,7,8].filter(i=>movable(i,empty)&&i!==last);const next=moves[Math.floor(Math.random()*moves.length)];[tiles[empty],tiles[next]]=[tiles[next],tiles[empty]];last=empty;empty=next;}if(tiles.join()==='1,2,3,4,5,6,7,8,0')return newSlide();slideState.textContent='並べ替えよう';drawSlide();}
function moveSlide(dir){if(activeGame!=='slide')return;const empty=tiles.indexOf(0),row=Math.floor(empty/3),col=empty%3;const target={ArrowLeft:col<2?empty+1:-1,ArrowRight:col>0?empty-1:-1,ArrowUp:row<2?empty+3:-1,ArrowDown:row>0?empty-3:-1}[dir];if(target<0)return;[tiles[empty],tiles[target]]=[tiles[target],tiles[empty]];drawSlide();if(tiles.join()==='1,2,3,4,5,6,7,8,0')slideState.textContent='CLEAR!';}document.getElementById('slide-new').onclick=newSlide;newSlide();

/* --- パズル2：答えを内製したシーザー暗号。必ず正解選択肢が1つある --- */
const words=['DREAM','AQUA','ORBIT','CLOUD','SIGNAL','BUBBLE'],cipherCode=document.getElementById('cipher-code'),cipherHint=document.getElementById('cipher-hint'),cipherOptions=document.getElementById('cipher-options'),cipherState=document.getElementById('cipher-state');let cipher={};
function shift(word,n){return [...word].map(c=>String.fromCharCode((c.charCodeAt(0)-65+n+26)%26+65)).join('');}
function newCipher(){const answer=words[Math.floor(Math.random()*words.length)],n=1+Math.floor(Math.random()*6),opts=new Set([answer]);while(opts.size<4)opts.add(words[Math.floor(Math.random()*words.length)]);cipher={answer,n,opts:[...opts].sort(()=>Math.random()-.5),selected:0};cipherCode.textContent=shift(answer,n);cipherHint.textContent=`ヒント：アルファベットを ${n} 文字もどす`;cipherState.textContent='信号を読む';drawCipher();}
function drawCipher(){cipherOptions.innerHTML='';cipher.opts.forEach((v,i)=>{const b=document.createElement('button');b.className=i===cipher.selected?'selected':'';b.textContent=v;b.onclick=()=>{cipher.selected=i;answerCipher();};cipherOptions.appendChild(b);});}
function answerCipher(){if(cipher.opts[cipher.selected]===cipher.answer){cipherState.textContent='解読成功！';setTimeout(()=>{if(activeGame==='cipher')newCipher();},650)}else{cipherState.textContent='もう一度、信号を見てみよう';}}
document.getElementById('cipher-hint-button').onclick=()=>cipherHint.textContent=`「${cipherCode.textContent}」は ${cipher.answer} を ${cipher.n} 文字先へずらした信号`;newCipher();

/* --- パズル3：DFSで迷路を掘り、BFSで開始から出口までを必ず検証 --- */
const mazeBoard=document.getElementById('maze-board'),mazeState=document.getElementById('maze-state');let maze=[],mazePos=0;const N=5;
function neighbors(i){const r=Math.floor(i/N),c=i%N;return [[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([y,x])=>y>=0&&y<N&&x>=0&&x<N).map(([y,x])=>y*N+x);}
function validMaze(){const q=[0],seen=new Set(q);while(q.length){const i=q.shift();if(i===N*N-1)return true;maze[i].forEach(j=>{if(!seen.has(j)){seen.add(j);q.push(j)}})}return false;}
function newMaze(){do{maze=Array.from({length:N*N},()=>[]);const seen=new Set([0]),stack=[0];while(stack.length){const cur=stack[stack.length-1],next=neighbors(cur).filter(n=>!seen.has(n));if(!next.length){stack.pop();continue}const n=next[Math.floor(Math.random()*next.length)];seen.add(n);maze[cur].push(n);maze[n].push(cur);stack.push(n);}}while(!validMaze());mazePos=0;mazeState.textContent='出口を探して';drawMaze();}
function drawMaze(){mazeBoard.innerHTML='';for(let i=0;i<N*N;i++){const cell=document.createElement('span');cell.className='maze-cell';if(i===mazePos)cell.classList.add('player');if(i===N*N-1)cell.classList.add('goal');const top=i-N,right=i+1,bottom=i+N,left=i-1;cell.style.borderTop=maze[i].includes(top)?'0':'2px solid #1674a8';cell.style.borderRight=i%N!==N-1&&maze[i].includes(right)?'0':'2px solid #1674a8';cell.style.borderBottom=maze[i].includes(bottom)?'0':'2px solid #1674a8';cell.style.borderLeft=i%N&&maze[i].includes(left)?'0':'2px solid #1674a8';cell.textContent=i===mazePos?'●':i===N*N-1?'✦':'';mazeBoard.appendChild(cell);}}
function moveMaze(dir){if(activeGame!=='maze')return;const next={ArrowLeft:mazePos-1,ArrowRight:mazePos+1,ArrowUp:mazePos-N,ArrowDown:mazePos+N}[dir];if(next===undefined||!maze[mazePos].includes(next))return;mazePos=next;drawMaze();if(mazePos===N*N-1)mazeState.textContent='CLEAR! 新しい海図も作れます。';}document.getElementById('maze-new').onclick=newMaze;newMaze();

/* 共通操作：矢印キーと横・縦スワイプ。短いタップは無視 */
window.addEventListener('keydown',e=>{const dir={ArrowLeft:'ArrowLeft',ArrowRight:'ArrowRight',ArrowUp:'ArrowUp',ArrowDown:'ArrowDown',a:'ArrowLeft',d:'ArrowRight',w:'ArrowUp',s:'ArrowDown'}[e.key];if(activeGame==='deep'&&dir){keys.add(dir);e.preventDefault();return}if(activeGame==='slide'&&dir){moveSlide(dir);e.preventDefault()}if(activeGame==='maze'&&dir){moveMaze(dir);e.preventDefault()}if(activeGame==='cipher'){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){cipher.selected=(cipher.selected+(e.key==='ArrowLeft'?-1:1)+4)%4;drawCipher();e.preventDefault()}if(e.key==='ArrowUp'||e.key==='Enter'){answerCipher();e.preventDefault()}}});window.addEventListener('keyup',e=>{const dir={ArrowLeft:'ArrowLeft',ArrowRight:'ArrowRight',ArrowUp:'ArrowUp',ArrowDown:'ArrowDown',a:'ArrowLeft',d:'ArrowRight',w:'ArrowUp',s:'ArrowDown'}[e.key];if(dir)keys.delete(dir);});
cv.addEventListener('pointerdown',e=>{if(deepRun){deep.drag=true;cv.setPointerCapture(e.pointerId)}});cv.addEventListener('pointermove',e=>{if(deepRun&&deep.drag){const r=cv.getBoundingClientRect();deep.sub.x=(e.clientX-r.left)*cv.width/r.width;deep.sub.y=(e.clientY-r.top)*cv.height/r.height}});cv.addEventListener('pointerup',()=>{if(deep)deep.drag=false});let swipeStart;document.querySelector('.game-stage').addEventListener('touchstart',e=>{swipeStart=e.touches[0]},{passive:true});document.querySelector('.game-stage').addEventListener('touchend',e=>{if(!swipeStart)return;const t=e.changedTouches[0],dx=t.clientX-swipeStart.clientX,dy=t.clientY-swipeStart.clientY;swipeStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<35)return;const dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'ArrowRight':'ArrowLeft'):(dy>0?'ArrowDown':'ArrowUp');if(activeGame==='slide')moveSlide(dir);if(activeGame==='maze')moveMaze(dir);if(activeGame==='cipher'&&(dir==='ArrowLeft'||dir==='ArrowRight')){cipher.selected=(cipher.selected+(dir==='ArrowLeft'?-1:1)+4)%4;drawCipher();}},{passive:true});
function selectGame(name){stopTap();stopDeep();activeGame=name;Object.entries(panels).forEach(([key,p])=>p.hidden=key!==name);choices.forEach(c=>c.classList.toggle('active',c.dataset.game===name));}choices.forEach(c=>c.onclick=()=>selectGame(c.dataset.game));
